---
eureka:
  client:
    serviceUrl:
        defaultZone: http://172.18.100.10:8010/eureka/, http://172.17.0.3:8010/eureka/,http://localhost:8010/eureka/,http://192.168.0.3:8010/eureka/
        
test:
  value: yannick
        
---
spring:
  profiles: subject
words: I,You,He,She,We,They
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog  

